server:
  port: 8081

# Habilita o console web do H2
spring:
  h2:
    console:
      enabled: true
  # Configuracao da fonte de dados
  datasource:
    url: jdbc:h2:mem:d01291ac-d484-4e73-a2d5-a93eaf1e6793
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # JPA e Hibernate config
  jpa:
    hibernate:
      ddl-auto: update
